[config]
skip_core_tasks = true

# コード生成（freezedなど）
[tasks.runner]
script = 'fvm flutter pub run build_runner build --delete-conflicting-outputs'

# flutter run （フェイクデータを使用）
[tasks.fun]
dependencies = ["runner"]
script = 'fvm flutter run --dart-define DataType=fake ${@}'

# flutter run （本番データを使用）
[tasks.run]
dependencies = ["runner"]
script = 'fvm flutter run --dart-define DataType=real ${@}'

# GitHubへPush
[tasks.push]
script = '''
fvm dart fix --apply
fvm dart format lib/
fvm dart format test/
git add .
git commit -m "format" || echo "No changes to commit"
git push
'''

# テスト
[tasks.test]
dependencies = ["runner"]
script = 'fvm flutter test'

