# コード生成（freezedなど）
[tasks.runner]
script = 'flutter pub run build_runner build --delete-conflicting-outputs'

# flutter run （フェイクデータを使用）
[tasks.fun]
script = 'flutter run --dart-define DataType=fake'

# flutter run （本番データを使用）
[tasks.run]
script = 'flutter run --dart-define DataType=real'

# GitHubへPush
[tasks.push]
script = '''
dart fix --apply
dart format lib/
dart format test/
git push
'''
