name: yumemi_flutter_codecheck
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_octicons: ^0.37.0
  primer_progress_bar: ^0.2.1
  github_language_colors: ^1.0.1

  # 文字列のフォーマット
  intl: ^0.18.1

  # ネットワーク
  http: ^1.1.0

  # ルーティング
  go_router: ^9.0.3

  # 状態管理
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6

  # コード生成
  freezed_annotation: ^2.2.0

  # 静的解析
  meta: ^1.9.1

  # フェイクデータ
  faker: ^2.1.0

  # ログ
  logging: ^1.2.0
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # コード生成
  build_runner: ^2.4.6
  freezed: ^2.3.5

flutter:
  uses-material-design: true
