name: GitHub Pagesへのデプロイ
on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  deploy-example:
    name: Deploy the app to GitHub Pages
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter version
        uses: kuhnroyal/flutter-fvm-config-action@v1
        id: fvm-config-action

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build web app
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
