name: プルリクエストの検証
run-name: Validation for ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [master]
env:
  package_dir: ./
jobs:
  validation:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter versioin
        run: flutter --version

      - name: Install dependencies
        working-directory: ${{ env.package_dir }}
        run: flutter pub get

      - name: Build runner
        working-directory: ${{ env.package_dir }}
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analize
        working-directory: ${{ env.package_dir }}
        run: flutter analyze

      - name: Tests
        working-directory: ${{ env.package_dir }}
        run: flutter test

      - name: Build web app
        working-directory: ${{ env.package_dir }}
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"
